Repository FranckKe/mersea, pull requests merged in 2018-04, with the labels that each got.

#120 [master] Add language to user
  Gemfile
  Gemfile.lock
  app/assets/javascripts/views/pages_index.js
  app/assets/javascripts/views/users_me.js
  app/controllers/application_controller.rb
  app/controllers/users/registrations_controller.rb
  app/controllers/users_controller.rb
  app/models/user.rb
  app/views/layouts/_topbar.html.erb
  app/views/users/me.html.erb
  config/locales/en.yml
  config/locales/es.yml
  config/locales/fr.yml
  db/migrate/20180331151629_add_language_to_users.rb
  db/schema.rb
Labels: enhancement

#123 [master] Disable Uglifier when EXECJS_RUNTIME is Disabled
  Gemfile
  config/environments/production.rb
Labels: bug

#124 [master] Fix datepicker date format conflict with i18n
  app/assets/javascripts/views/devise_password.js
  app/assets/javascripts/views/devise_registration.js
  app/assets/javascripts/views/devise_session.js
  app/assets/javascripts/views/reports_new.js
  app/assets/javascripts/views/users_me.js
  app/assets/stylesheets/base/helpers.scss
  app/assets/stylesheets/components/card.scss
  app/controllers/reports_controller.rb
  app/controllers/users_controller.rb
  app/views/devise/passwords/_edit.html.erb
  app/views/reports/_edit.html.erb
  app/views/reports/_new.html.erb
  app/views/reports/edit.js.erb
  app/views/tracers/index.html.erb
  app/views/users/me.html.erb
  config/locales/en.yml
  config/locales/es.yml
  config/locales/fr.yml
Labels: bug, enhancement

#132 [master] Fix mailer
  app/mailers/postmark_devise_mailer.rb
  app/views/devise/passwords/edit.html.erb
Labels: bug
