Repository FranckKe/mersea, pull requests merged in 2019-04, with the labels that each got.

#248 [pu-2.0] Merge after #247 - Fathom analytics
  Dockerfile
  frontend/.env.sample
  frontend/package.json
  frontend/public/index.html
  frontend/src/components/AddReport.vue
  frontend/src/components/tools/FilterReportsByDate.vue
  frontend/src/main.js
  frontend/src/router.js
  frontend/src/store/modules/pages.js
  frontend/src/store/modules/reports.js
  frontend/src/store/modules/tracers.js
  frontend/src/views/Home.vue
  frontend/yarn.lock
Labels: enhancement

#249 [pu-2.0] Improve overall styling
  frontend/package.json
  frontend/src/App.vue
  frontend/src/components/AddReport.vue
  frontend/src/components/MenuNav.vue
  frontend/src/components/Tool.vue
  frontend/src/components/ToolBar.vue
  frontend/src/components/tools/FilterReportsByDate.vue
  frontend/src/components/tools/FilterReportsByTracer.vue
  frontend/src/main.js
  frontend/src/views/Home.vue
  frontend/src/views/Page.vue
Labels: enhancement

#256 Update yarn.lock for 2.0
  frontend/yarn.lock
Labels: bug

#257 Fix coordinates decimals
  app/controllers/reports_controller.rb
  frontend/src/components/AddReport.vue
Labels: enhancement

#258 [master] Css tweak and fixes
  frontend/public/favicon.ico
  frontend/public/img/icons/android-chrome-192x192.png
  frontend/public/img/icons/android-chrome-384x384.png
  frontend/public/img/icons/android-chrome-512x512.png
  frontend/public/img/icons/apple-touch-icon-120x120.png
  frontend/public/img/icons/apple-touch-icon-152x152.png
  frontend/public/img/icons/apple-touch-icon-180x180.png
  frontend/public/img/icons/apple-touch-icon-60x60.png
  frontend/public/img/icons/apple-touch-icon-76x76.png
  frontend/public/img/icons/apple-touch-icon.png
  frontend/public/img/icons/browserconfig.xml
  frontend/public/img/icons/favicon-16x16.png
  frontend/public/img/icons/favicon-32x32.png
  frontend/public/img/icons/msapplication-icon-144x144.png
  frontend/public/img/icons/mstile-150x150.png
  frontend/public/img/icons/safari-pinned-tab.svg
  frontend/public/index.html
  frontend/public/manifest.json
  frontend/src/App.vue
  frontend/src/components/AddReport.vue
  frontend/src/components/Tool.vue
  frontend/src/components/TracersGrid.vue
  frontend/src/components/tools/FilterReportsByDate.vue
  frontend/src/components/tools/FilterReportsByTracer.vue
  frontend/src/views/Home.vue
  frontend/src/views/Leaderboard.vue
  frontend/src/views/Page.vue
  frontend/src/views/Tracers.vue
Labels: bug, enhancement

#259 [master] Refactor i18n
  app/controllers/api_controller.rb
  app/controllers/application_controller.rb
  frontend/.env.sample
  frontend/src/components/MenuNav.vue
  frontend/src/i18n.js
  frontend/src/main.js
  frontend/src/store/index.js
  frontend/src/views/Login.vue
  frontend/vue.config.js
Labels: back, bug, enhancement, front

#262 [master] Fix analytics url + qol improvements
  frontend/public/index.html
  frontend/src/components/AddReport.vue
  frontend/src/components/MenuNav.vue
  frontend/src/components/ToolBar.vue
  frontend/src/views/Tracers.vue
Labels: bug, enhancement, front

#263 [master] Fix tracer url i18n
  frontend/src/App.vue
  frontend/src/components/AddReport.vue
  frontend/src/components/MenuNav.vue
  frontend/src/components/TracersGrid.vue
  frontend/src/components/TracersList.vue
  frontend/src/components/tools/FilterReportsByTracer.vue
  frontend/src/main.js
  frontend/src/router.js
  frontend/src/views/Home.vue
  frontend/src/views/Leaderboard.vue
  frontend/src/views/MyReports.vue
  frontend/yarn.lock
Labels: bug, enhancement

#264 [master] Fix español tracers page
  frontend/src/components/LangSwitcher.vue
  frontend/src/router.js
  frontend/src/views/Me.vue
Labels: bug
